remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Equivariant 4D Panoptic Segmentation
description: This is the project page for the paper: 4D Panoptic Segmentation as Invariant and Equivariant Field Prediction (ICCV 2023). The code will be released soon. 
